#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

RUN_TAG="${HRM_AUDIO_FORMAL_SMOKE_RUN_TAG:-$(date +%Y%m%d-%H%M%S)}"
export HRM_AUDIO_TRAINER_SMOKE_RUN_DIR="${HRM_AUDIO_FORMAL_SMOKE_RUN_DIR:-$REPO_ROOT/outputs/hrm_text/audio_trainer_smoke_formal_b8ga4_r16/$RUN_TAG}"
export HRM_AUDIO_TRAINER_SMOKE_OUTPUT_REPORT="${HRM_AUDIO_FORMAL_SMOKE_OUTPUT_REPORT:-$HRM_AUDIO_TRAINER_SMOKE_RUN_DIR/trainer_smoke_report.json}"

export HRM_AUDIO_TRAINER_SMOKE_MICRO_BATCH_SIZE=8
export HRM_AUDIO_TRAINER_SMOKE_GRADIENT_ACCUMULATION_STEPS=4
export HRM_AUDIO_TRAINER_SMOKE_LORA_RANK=16
export HRM_AUDIO_TRAINER_SMOKE_LORA_ALPHA=32
export HRM_AUDIO_TRAINER_SMOKE_LORA_DROPOUT=0.05
export HRM_AUDIO_TRAINER_SMOKE_LEARNING_RATE=1e-4
export HRM_AUDIO_TRAINER_SMOKE_ALIGNER_LEARNING_RATE=1e-4

exec bash "$SCRIPT_DIR/smoke_hrm_audio_swift_trainer.sh"
